<?php

use App\Models\Mood;
use Illuminate\Database\Seeder;

class MoodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $moods = [
            ['name' => 'Admirando 1', 'image' => 'admire.gif', 'points' => 10],
            ['name' => 'Admirando 2', 'image' => 'admire2.gif', 'points' => 10],
            ['name' => 'Ahaaah', 'image' => 'ahaaah.gif', 'points' => 10],
            ['name' => 'Anjo 1', 'image' => 'angel1.gif', 'points' => 10],
            ['name' => 'Anjo 2', 'image' => 'angel2.gif', 'points' => 10],
            ['name' => 'Mau Atmosfera', 'image' => 'bad-atmosphere.gif', 'points' => 10],
            ['name' => 'Beaten', 'image' => 'beaten.gif', 'points' => 10],
            ['name' => 'Beg', 'image' => 'beg.gif', 'points' => 10],
            ['name' => 'Big Eye', 'image' => 'big-eye.gif', 'points' => 10],
            ['name' => 'Bike', 'image' => 'bike.gif', 'points' => 10],
            ['name' => 'Bird', 'image' => 'bird.gif', 'points' => 10],
            ['name' => 'Bled 1', 'image' => 'bled1.gif', 'points' => 10],
            ['name' => 'Bled 2', 'image' => 'bled2.gif', 'points' => 10],
            ['name' => 'Bleeding', 'image' => 'bleeding.gif', 'points' => 10],
            ['name' => 'Blocked', 'image' => 'blocked.gif', 'points' => 10],
            ['name' => 'Bsod', 'image' => 'bsod.gif', 'points' => 10],
            ['name' => 'Bye 1', 'image' => 'bye1.gif', 'points' => 10],
            ['name' => 'Bye 2', 'image' => 'bye2.gif', 'points' => 10],
            ['name' => 'Cheer 1', 'image' => 'cheer1.gif', 'points' => 10],
            ['name' => 'Cheer 2', 'image' => 'cheer2.gif', 'points' => 10],
            ['name' => 'Cheer 3', 'image' => 'cheer3.gif', 'points' => 10],
            ['name' => 'Confused', 'image' => 'confused.gif', 'points' => 10],
            ['name' => 'Congrats', 'image' => 'congrats.gif', 'points' => 10],
            ['name' => 'Cool', 'image' => 'cool.gif', 'points' => 10],
            ['name' => 'Cruch', 'image' => 'cruch.gif', 'points' => 10],
            ['name' => 'Crying 1', 'image' => 'crying1.gif', 'points' => 10],
            ['name' => 'Crying 2', 'image' => 'crying2.gif', 'points' => 10],
            ['name' => 'Crying 3', 'image' => 'crying3.gif', 'points' => 10],
            ['name' => 'Cute 1', 'image' => 'cute1.gif', 'points' => 10],
            ['name' => 'Cute 2', 'image' => 'cute2.gif', 'points' => 10],
            ['name' => 'Dead', 'image' => 'dead.gif', 'points' => 10],
            ['name' => 'Depressed 1', 'image' => 'depressed1.gif', 'points' => 10],
            ['name' => 'Depressed 2', 'image' => 'depressed2.gif', 'points' => 10],
            ['name' => 'Desperate 1', 'image' => 'desperate1.gif', 'points' => 10],
            ['name' => 'Desperate 2', 'image' => 'desperate2.gif', 'points' => 10],
            ['name' => 'Dong', 'image' => 'dong.gif', 'points' => 10],
            ['name' => 'Dreaming', 'image' => 'dreaming.gif', 'points' => 10],
            ['name' => 'Dying', 'image' => 'dying.gif', 'points' => 10],
            ['name' => 'Eaten Alive', 'image' => 'eaten-alive.gif', 'points' => 10],
            ['name' => 'Eating Me', 'image' => 'eating-me.gif', 'points' => 10],
            ['name' => 'Embarrassed 1', 'image' => 'embarrassed1.gif', 'points' => 10],
            ['name' => 'Embarrassed 2', 'image' => 'embarrassed2.gif', 'points' => 10],
            ['name' => 'Embarrassed 3', 'image' => 'embarrassed3.gif', 'points' => 10],
            ['name' => 'Embarrassed 4', 'image' => 'embarrassed4.gif', 'points' => 10],
            ['name' => 'Evil Smile', 'image' => 'evil-smile.gif', 'points' => 10],
            ['name' => 'Expulsion', 'image' => 'expulsion.gif', 'points' => 10],
            ['name' => 'Falling Asleep', 'image' => 'falling-asleep.gif', 'points' => 10],
            ['name' => 'Freezing', 'image' => 'freezing.gif', 'points' => 10],
            ['name' => 'Frozen', 'image' => 'frozen.gif', 'points' => 10],
            ['name' => 'Full', 'image' => 'full.gif', 'points' => 10],
            ['name' => 'Ghost', 'image' => 'ghost.gif', 'points' => 10],
            ['name' => 'Good Job', 'image' => 'good-job.gif', 'points' => 10],
            ['name' => 'Good Luck', 'image' => 'good-luck.gif', 'points' => 10],
            ['name' => 'Happy Birthday', 'image' => 'happy-birth-day1.gif', 'points' => 10],
            ['name' => 'Happy', 'image' => 'happy.gif', 'points' => 10],
            ['name' => 'Hate', 'image' => 'hate.gif', 'points' => 10],
            ['name' => 'Hehe', 'image' => 'hehe.gif', 'points' => 10],
            ['name' => 'Hell Yes', 'image' => 'hell-yes.gif', 'points' => 10],
            ['name' => 'Help', 'image' => 'help.gif', 'points' => 10],
            ['name' => 'Hi', 'image' => 'hi.gif', 'points' => 10],
            ['name' => 'Hot 1', 'image' => 'hot1.gif', 'points' => 10],
            ['name' => 'Hot 2', 'image' => 'hot2.gif', 'points' => 10],
            ['name' => 'Hypnosis', 'image' => 'hypnosis.gif', 'points' => 10],
            ['name' => 'Ill', 'image' => 'ill.gif', 'points' => 10],
            ['name' => 'Info', 'image' => 'info.gif', 'points' => 10],
            ['name' => 'Innocent', 'image' => 'innocent.gif', 'points' => 10],
            ['name' => 'Kick', 'image' => 'kick.gif', 'points' => 10],
            ['name' => 'Kicked 1', 'image' => 'kicked1.gif', 'points' => 10],
            ['name' => 'Kicked 2', 'image' => 'kicked2.gif', 'points' => 10],
            ['name' => 'Lie', 'image' => 'lie.gif', 'points' => 10],
            ['name' => 'Lol 1', 'image' => 'lol1.gif', 'points' => 10],
            ['name' => 'Lol 2', 'image' => 'lol2.gif', 'points' => 10],
            ['name' => 'Lonely', 'image' => 'lonely.gif', 'points' => 10],
            ['name' => 'Love', 'image' => 'love.gif', 'points' => 10],
            ['name' => 'Meh', 'image' => 'meh.gif', 'points' => 10],
            ['name' => 'Nonono', 'image' => 'nonono.gif', 'points' => 10],
            ['name' => 'Noooo', 'image' => 'noooo.gif', 'points' => 10],
            ['name' => 'Not Listening', 'image' => 'not-listening.gif', 'points' => 10],
            ['name' => 'Objection', 'image' => 'objection.gif', 'points' => 10],
            ['name' => 'Oh', 'image' => 'oh.gif', 'points' => 10],
            ['name' => 'Payup', 'image' => 'payup.gif', 'points' => 10],
            ['name' => 'Pff 1', 'image' => 'pff1.gif', 'points' => 10],
            ['name' => 'Pff 2', 'image' => 'pff2.gif', 'points' => 10],
            ['name' => 'Pointing', 'image' => 'pointing.gif', 'points' => 10],
            ['name' => 'Pretty', 'image' => 'pretty.gif', 'points' => 10],
            ['name' => 'Punch', 'image' => 'punch.gif', 'points' => 10],
            ['name' => 'Push Up', 'image' => 'push-up.gif', 'points' => 10],
            ['name' => 'Relax 1', 'image' => 'relax1.gif', 'points' => 10],
            ['name' => 'Relax 2', 'image' => 'relax2.gif', 'points' => 10],
            ['name' => 'Robot', 'image' => 'robot.gif', 'points' => 10],
            ['name' => 'Running', 'image' => 'running.gif', 'points' => 10],
            ['name' => 'Scared', 'image' => 'scared.gif', 'points' => 10],
            ['name' => 'Scary', 'image' => 'scary.gif', 'points' => 10],
            ['name' => 'Serenade', 'image' => 'serenade.gif', 'points' => 10],
            ['name' => 'Shock 1', 'image' => 'shock1.gif', 'points' => 10],
            ['name' => 'Shock 2', 'image' => 'shock2.gif', 'points' => 10],
            ['name' => 'Shy', 'image' => 'shy.gif', 'points' => 10],
            ['name' => 'Sigh', 'image' => 'sigh.gif', 'points' => 10],
            ['name' => 'Silence', 'image' => 'silence.gif', 'points' => 10],
            ['name' => 'Sleeping', 'image' => 'sleeping.gif', 'points' => 10],
            ['name' => 'Smoking 1', 'image' => 'smoking1.gif', 'points' => 10],
            ['name' => 'Smoking 2', 'image' => 'smoking2.gif', 'points' => 10],
            ['name' => 'Spa', 'image' => 'spa.gif', 'points' => 10],
            ['name' => 'Starving', 'image' => 'starving.gif', 'points' => 10],
            ['name' => 'Steal', 'image' => 'steal.gif', 'points' => 10],
            ['name' => 'Stoned', 'image' => 'stoned.gif', 'points' => 10],
            ['name' => 'Stress', 'image' => 'stress.gif', 'points' => 10],
            ['name' => 'Studying', 'image' => 'studying.gif', 'points' => 10],
            ['name' => 'Super Sayan', 'image' => 'super-sayan.gif', 'points' => 10],
            ['name' => 'Super', 'image' => 'super.gif', 'points' => 10],
            ['name' => 'Sweating', 'image' => 'sweating.gif', 'points' => 10],
            ['name' => 'Sweetdrop', 'image' => 'sweetdrop.gif', 'points' => 10],
            ['name' => 'Tar', 'image' => 'tar.gif', 'points' => 10],
            ['name' => 'Uhuhuh', 'image' => 'uhuhuh.gif', 'points' => 10],
            ['name' => 'Victory', 'image' => 'victory.gif', 'points' => 10],
            ['name' => 'Vomiting', 'image' => 'vomiting.gif', 'points' => 10],
            ['name' => 'Wait', 'image' => 'wait.gif', 'points' => 10],
            ['name' => 'Waiting', 'image' => 'waiting.gif', 'points' => 10],
            ['name' => 'Warning', 'image' => 'warning.gif', 'points' => 10],
            ['name' => 'Washing', 'image' => 'washing.gif', 'points' => 10],
            ['name' => 'Wet', 'image' => 'wet.gif', 'points' => 10],
            ['name' => 'Wew', 'image' => 'wew.gif', 'points' => 10],
            ['name' => 'Whaaat 1', 'image' => 'whaaat1.gif', 'points' => 10],
            ['name' => 'Whaaat 2', 'image' => 'whaaat2.gif', 'points' => 10],
            ['name' => 'Whaaat 3', 'image' => 'whaaat3.gif', 'points' => 10],
            ['name' => 'What', 'image' => 'what.gif', 'points' => 10],
            ['name' => 'Whip', 'image' => 'whip.gif', 'points' => 10],
            ['name' => 'Whistling', 'image' => 'whistling.gif', 'points' => 10],
            ['name' => 'Woa', 'image' => 'woa.gif', 'points' => 10],
            ['name' => 'Work', 'image' => 'work.gif', 'points' => 10],
            ['name' => 'Wow 1', 'image' => 'wow1.gif', 'points' => 10],
            ['name' => 'Wow 2', 'image' => 'wow2.gif', 'points' => 10],
            ['name' => 'Yawn', 'image' => 'yawn.gif', 'points' => 10]
        ];

        foreach ($moods as $mood) {
            Mood::create($mood);
        }
    }
}
